install:
sudo: false
language: java

cache:
  directories:
    - $HOME/.m2/repository

jdk:
    - openjdk8

script:
    - mvn -B clean jacoco:prepare-agent install jacoco:report
    - bash <(curl -s https://codecov.io/bash)
